waypointMgr:
  waypoint_radius : 100 # meters (used only for the first waypoint)

lineFollowing:
  loop_rate : 1.  # Hz
  incidence_angle : 45 # degrees
  max_distance_from_line : 30. # meters at the distance targetAngle = incidence_angle/2
  gain_I : 0.
  gain_D : 0.

courseRegulator:
  loop_rate : 10.  # Hz
  max_helm_angle : 7  # degrees
  regulator_type : 2   # 1: sinus, 2: PID
  PID :
    gain_P : 0.1
    gain_I : 0
    gain_D : 0.2

imu:
  magnetic_declination : -1.5  # degrees
