waypointMgr:
  waypoint_radius : 100 # meters (used only for the first waypoint)

lineFollowing:
  loop_rate : 10.  # Hz
  incidence_angle : 45 # degrees
  max_distance_from_line : 10. # meters at the distance targetAngle = incidence_angle/2
  gain_I : 0.
  gain_D : 0.

courseRegulator:
  loop_rate : 10.  # Hz
  max_helm_angle : 7  # degrees
  regulator_type : 3   # 1: sinus, 2: PID, 3: PIDsin (sinus on the derivative term)
  PID :
    gain_P : 0.1
    gain_I : 0
    gain_D : 0.2
  offset_motor_angle : 5. # degrees

imu:
  magnetic_declination : -1.5  # degrees
